In [33]:
import numpy as np
#Create a simple numpy Array
myFirstNumpyArray = np.arange(2,10)
print(myFirstNumpyArray)

[2 3 4 5 6 7 8 9]


In [34]:
#Convert a python list to numpy array
pList = [1,2,3,4,5,6,7,8,9]
numpyArray = np.array(pList)
type(numpyArray)
print(numpyArray)

[1 2 3 4 5 6 7 8 9]


In [110]:
#one can multiply/add some number to numpy which will effect all eleements of the array
numpyArray+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
numpyArray*4  # original array 

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [113]:
#whats the type of numpyArray
type(numpyArray)

numpy.ndarray

In [159]:
#what if I devide array or if we process inverse. inf(infinity) is produced when we take inverse. numpy didn't produce an error
#but throw a warning. 
a = np.arange(0,11)
1/a

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [163]:
#Lets create numpy array or initialize
arr = np.array([0,1,2,3,4,5,6,7,8,9]) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
#Lets create 2D array
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [170]:
#lets check the shape 
np.shape(arr_2d)

(3, 3)

In [173]:
#lets add element in every row and in every column
arr_2d.sum(axis=0)

array([ 9, 12, 15])

In [175]:
#Column wise
arr_2d.sum(axis=1)

array([ 3, 12, 21])

In [176]:
#Just sum all elements
arr_2d.sum()

36

In [179]:
sum =0
for i in np.arange(0,9):
    sum=sum+i
print (sum)

36


In [117]:
#Lets play around numpy Array.
array = np.arange(0,11) # 0 to 11 (not including 11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [118]:
#lets get section of this array
print(array[0:5]) #or array[:5]

array[1:5]

[0 1 2 3 4]


array([1, 2, 3, 4])

In [119]:
#lets explore arange function

a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [182]:
#generate even numbers
b = np.arange(0,11,2) #start, end, step
b


array([ 0,  2,  4,  6,  8, 10])

In [120]:
#lets get the part of this array
small=a[3:8]
small

array([3, 4, 5, 6, 7])

In [121]:
small[:]=100

In [122]:
#Guess what happened to our original array
a

array([  0,   1,   2, 100, 100, 100, 100, 100,   8,   9,  10,  11])

In [123]:
#so you want to avoid this effect then use copy function
s = a.copy()[3:9]



In [124]:
s[:] = 89
s

array([89, 89, 89, 89, 89, 89])

In [125]:
#original array
print(a)
s

[  0   1   2 100 100 100 100 100   8   9  10  11]


array([89, 89, 89, 89, 89, 89])

In [126]:
#Convert a two Dimentional Array to Numpy Array
twoDimlist =[[1,2,3],[4,5,6],[7,8,9]]
npMatrix = np.array(twoDimlist)
print(npMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
#Exploring arange method
print(np.arange(0,10,1)) # start at 0, Till 10(Not including) at step 1
print(np.arange(0,20,1))
print(np.arange(1,19,2))  # Starts at 1, Ends at 19(Not including) at step 2. So it will stop 17.


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17]


In [128]:
#Zeros and Ones
np.zeros(2)

array([0., 0.])

In [129]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [130]:
s = (4, 2)
np.zeros(s,dtype=int,order='C') # default order is C ---> Major Rows

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [131]:
#Line Space
#Need numbers, including first and last number, Generate 3 number at equi distance
np.linspace(0,10,3) #

array([ 0.,  5., 10.])

In [132]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [133]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [134]:
# # Random Number, Lets explore all possible ways to generate random numbers using Numpy


In [135]:
np.random.rand(10)

array([0.67413362, 0.44183317, 0.43401399, 0.61776698, 0.51313824,
       0.65039718, 0.60103895, 0.8052232 , 0.52164715, 0.90864888])

In [136]:
#Generate single random number integer
np.random.randint(0,100)

88

In [137]:
#Generate n number of random rumbers between two numbers:
np.random.randint(0,100,10)

array([ 9, 15, 18, 80, 71, 88, 11, 17, 46,  7])

In [138]:
#If you want to persists the random state
np.random.seed(10)
print(np.random.randint(0,100))
print(np.random.randint(0,100,10))

9
[15 64 28 89 93 29  8 73  0 40]


In [139]:
#lets understand reshape
#You want an array to Matrix withoug changing the elements
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
arr=np.arange(0,10)
CStyleArr= arr.reshape(2,5,order='C')  #'C' Style -- Row wise
print(CStyleArr)
FStyleArr =arr.reshape(2,5,order='F')  # Fortran Style -- Column wise.
print(FStyleArr)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [141]:
#if you want to flatten the array
np.ravel(CStyleArr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.ravel(FStyleArr)

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [143]:
#Find Max, Min and its index

In [144]:
arr = np.random.randint(0,100,9)
arr

array([36, 16, 11, 54, 88, 62, 33, 72, 78])

In [145]:
arr.reshape(3,3)

array([[36, 16, 11],
       [54, 88, 62],
       [33, 72, 78]])

In [146]:
arr.max()
arr.argmax()

4

In [147]:
arr.min()
arr.argmin()

2

In [148]:
# 2D array
a = np.arange(0,25)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [149]:
#convert them to 2D array
a_2D=a.reshape(5,5)
a_2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
#lets say I wan to first two row
a_2D[0:2,]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [151]:
#lets get 4 column

a_2D[:,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [152]:
a_2D[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [153]:
a_2D[0::2] #alternate Rows

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [154]:
a_2D[:,0::2] # alternate Column

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [155]:
a_2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [156]:
a_2D[0::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [157]:
#Conditional Operation
a = np.arange(0,10)
b = a>5


In [158]:
#lets extract numbers which are more than 5 or just pass array b to a, i.e,
a[b]

array([6, 7, 8, 9])