In [2]:
import numpy as np
#Create a simple numpy Array
myFirstNumpyArray = np.arange(2,10)
print(myFirstNumpyArray)

[2 3 4 5 6 7 8 9]


In [3]:
#Convert a python list to numpy array
pList = [1,2,3,4,5,6,7,8,9]
numpyArray = np.array(pList)
type(numpyArray)
print(numpyArray)

[1 2 3 4 5 6 7 8 9]


In [4]:
#Convert a two Dimentional Array to Numpy Array
twoDimlist =[[1,2,3],[4,5,6],[7,8,9]]
npMatrix = np.array(twoDimlist)
print(npMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Exploring arange method
print(np.arange(0,10,1)) # start at 0, Till 10(Not including) at step 1
print(np.arange(0,20,1))
print(np.arange(1,19,2))  # Starts at 1, Ends at 19(Not including) at step 2. So it will stop 17.


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17]


In [6]:
#Zeros and Ones
np.zeros(2)

array([0., 0.])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
s = (4, 2)
np.zeros(s,dtype=int,order='C') # default order is C ---> Major Rows

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [9]:
#Line Space
#Need numbers, including first and last number, Generate 3 number at equi distance
np.linspace(0,10,3) #

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [11]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# # Random Number, Lets explore all possible ways to generate random numbers using Numpy


In [12]:
np.random.rand(10)

array([0.68901609, 0.81126802, 0.62949669, 0.94919476, 0.54883423,
       0.42187296, 0.96011853, 0.36154042, 0.88951645, 0.5023081 ])

In [13]:
#Generate single random number integer
np.random.randint(0,100)

97

In [14]:
#Generate n number of random rumbers between two numbers:
np.random.randint(0,100,10)

array([75, 96, 74, 93, 71, 61, 32, 35, 58, 32])

In [15]:
#If you want to persists the random state
np.random.seed(10)
print(np.random.randint(0,100))
print(np.random.randint(0,100,10))

9
[15 64 28 89 93 29  8 73  0 40]


In [16]:
#lets understand reshape
#You want an array to Matrix withoug changing the elements
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr=np.arange(0,10)
CStyleArr= arr.reshape(2,5,order='C')  #'C' Style -- Row wise
print(CStyleArr)
FStyleArr =arr.reshape(2,5,order='F')  # Fortran Style -- Column wise.
print(FStyleArr)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [18]:
#if you want to flatten the array
np.ravel(CStyleArr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.ravel(FStyleArr)

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [20]:
#Find Max, Min and its index

In [22]:
arr = np.random.randint(0,100,9)
arr

array([49, 51, 54, 77, 69, 13, 25, 13, 92])

In [24]:
arr.reshape(3,3)

array([[49, 51, 54],
       [77, 69, 13],
       [25, 13, 92]])

In [28]:
arr.max()
arr.argmax()

8

In [30]:
arr.min()
arr.argmin()

5